### ISSUE TITLE
version 1.1.6 doesn't skip file

### ISSUE THREAD

**Issue by bailih** [bendrucker/azure-blob-to-s3#11]
when I update to 1.1.6, it doesn't skip files which are already in the S3 even though their content length doesn't change. 
If I switch back to 1.1.5, it does skip a lot of old files.

**Comment by bendrucker** [comment]
The only related change is allowing minor versions of the aws-sdk:

https://github.com/bendrucker/azure-blob-to-s3/commit/0f4418d73c85aa82528ac2aaa738c0db07bc793b

There is a test that mocks the sdk to test content-length handling but obviously that wouldn't cover a regression coming from AWS. Can you debug a bit and see if anything looks unusual about the response headers?

**Comment by bailih** [comment]
Here is the log in 1.1.6:
{"time":"2019-03-28T18:09:34.507Z","hostname":"VirtualBox","pid":32295,"level":"debug","name":"s3","message":"head","object":{"AcceptRanges":"bytes","LastModified":"2019-03-28T17:47:01.000Z","ContentLength":2411,"ETag":"\"bc2xxxx03d\"","ContentType":"application/octet-stream","Metadata":{}},"filename":"xxxxlogs.v1.data"}

And here is the log in 1.1.5:
{"time":"2019-03-28T18:16:34.830Z","hostname":"VirtualBox","pid":32414,"level":"debug","name":"s3","message":"head","object":{"AcceptRanges":"bytes","LastModified":"Thu, 28 Mar 2019 18:09:37 GMT","ContentLength":"2411","ETag":"\"bcxxxxd\"","ContentType":"application/octet-stream","Metadata":{}},"filename":"xxxxlogs.v1.data"}

Looks like the 1.1.5's ContentLength is a string where 1.1.6's ContentLength is a number

**Comment by bendrucker** [comment]
> Looks like the 1.1.5's ContentLength is a string where 1.1.6's ContentLength is a number

Awesome, much appreciated! These values are returned as headers so they're inherently strings. Sounds like they made a (breaking) change to the client that parses the values into numbers.

The docs show a number now: https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#headObject-property

Looking at the API schema, `ContentLength` has been `{type: 'long'}` for a long time and `{type: 'integer'}` before that.

I'm at a bit of a loss to explain the change in behavior. I tried to confirm a theory that aws-sdk was supporting `BigInt` in node@10. I've wrestled with that choice in other libraries. Where we were previously returning strings (e.g. `int8` from Postgres) we could now return `BigInt`, but that would break existing users. Couldn't find anything to support that theory.

Azure definitely still returns strings:

https://azure.github.io/azure-storage-node/BlobResult.html

In the absence of any lead on a root cause I'll go ahead and conform to the new documented behavior in aws-sdk. Will either coerce both values to strings or numbers and compare from there.

**Comment by bailih** [comment]
Much appreciate your quick reaction.
Just one more question not related to this issue but bugging me for some time. I try to build a serverless lambda function to run this function but never succeed. Is this package suitable for serverless lambda function or it has to be run in a server?

**Comment by bendrucker** [comment]
> I try to build a serverless lambda function to run this function but never succeed. Is this package suitable for serverless lambda function or it has to be run in a server?

From a quick scan of the deps it should be compatible with node@6 and above. It's been a long time since I used this for a large migration but if I remember correctly I ran it from an EC2 instance, probably an m4.large for stable network bandwidth. Lambdas are time-limited to 15 mins so it's probably not a great idea to try to run this there. Should be possible as long as you have a small set of files.
